version: "3.8"

services:
  db:
    image: bybatkhuu/postgres:15.4-bookworm
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      PG_COLOR: ${PG_COLOR:-auto}
      POSTGRES_INITDB_ARGS: "${POSTGRES_INITDB_ARGS:--E UTF8 --locale=en_US.UTF-8}"
      POSTGRES_USER: ${FOT_DB_USERNAME:-fot_user}
      POSTGRES_PASSWORD: "${FOT_DB_PASSWORD:-fot_password1}"
      POSTGRES_DB: ${FOT_DB_DATABASE:-fot_db}
    volumes:
      - "./volumes/storage/postgresql/data:/var/lib/postgresql/data"
    tty: true

  api:
    image: bybatkhuu/fastapi-orm-template:1.0.2-231127
    depends_on:
      - db
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Asia/Seoul}
      FOT_APP_PORT: ${FOT_APP_PORT:-8000}
    volumes:
      - "./volumes/storage/fastapi-orm-template/logs:/var/log/fastapi-orm-template"
      - "./volumes/storage/fastapi-orm-template/data:/var/lib/fastapi-orm-template"
    ports:
      - "${FOT_APP_PORT:-8000}:${FOT_APP_PORT:-8000}"
    tty: true
