version: "3.8"

services:
  db:
    image: bybatkhuu/postgres:15.5-bookworm
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      PG_COLOR: ${PG_COLOR:-auto}
      POSTGRES_INITDB_ARGS: "${POSTGRES_INITDB_ARGS:--E UTF8 --locale=ko_KR.UTF-8 --lc-messages=en_AU.UTF-8 --lc-monetary=en_AU.UTF-8 --lc-numeric=en_AU.UTF-8 --lc-time=en_AU.UTF-8}"
      POSTGRES_USER: ${FOT_DB_USERNAME:-fot_user}
      POSTGRES_PASSWORD: "${FOT_DB_PASSWORD:-fot_password1}"
      POSTGRES_DB: ${FOT_DB_DATABASE:-fot_db}
    volumes:
      - "./volumes/storage/postgresql/conf.d:/etc/postgresql:ro"
      - "./volumes/storage/postgresql/data:/var/lib/postgresql/data"
    tty: true
    command: postgres -c "config_file=/etc/postgresql/postgresql.conf"

  api:
    image: bybatkhuu/rest.fastapi-orm-template:1.2.0-231130
    depends_on:
      - db
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Asia/Seoul}
      FOT_DB_HOST: ${FOT_DB_HOST:-db}
      FOT_APP_PORT: ${FOT_APP_PORT:-8000}
    volumes:
      - "./volumes/storage/rest.fastapi-orm-template/logs:/var/log/rest.fastapi-orm-template"
      - "./volumes/storage/rest.fastapi-orm-template/data:/var/lib/rest.fastapi-orm-template"
    ports:
      - "${FOT_APP_PORT:-8000}:${FOT_APP_PORT:-8000}"
    tty: true
