version: "3.8"

services:
  db:
    hostname: ${FOT_DB_HOST:-db}
    environment:
      PGPORT: ${FOT_DB_PORT:-5432}
    # volumes:
    #   - "./volumes/storage/postgresql/conf.d:/etc/postgresql:ro"
    #   - "./volumes/storage/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
    #   - "./volumes/storage/postgresql/logs:/var/log/postgresql"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    ports:
        - "${FOT_DB_PORT:-5432}:${FOT_DB_PORT:-5432}"

  # db-gui:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-fot_user@example.com}
  #     PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD:-fot_password1}"
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "db-gui-data:/var/lib/pgadmin"
  #   deploy:
  #     replicas: 0
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 512M
  #   ports:
  #     - "${PGADMIN_PORT:-8080}:80"

  api:
    image: bybatkhuu/fastapi-orm-template:latest
    env_file:
      - .env
    volumes:
      - "./volumes/storage/fastapi-orm-template/logs:${FOT_APP_LOGS_DIR:-/var/log/fastapi-orm-template}"
      - "./volumes/storage/fastapi-orm-template/data:${FOT_APP_DATA_DIR:-/var/lib/fastapi-orm-template}"
      - "./volumes/src/rest.fastapi-orm-template/scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/src/rest.fastapi-orm-template/app:/app/fastapi-orm-template"
      - "./volumes/.vscode-server:/home/fot-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "sleep 3 && uvicorn main:app --host=0.0.0.0 --port=${FOT_APP_PORT:-8000} --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log --reload --reload-include='*.yml' --reload-include='*.yaml' --reload-include='*.json'"]

# volumes:
#   db-gui-data:
