name: Deploy Production

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  deploy_production:
    name: Deploy
    runs-on: ubuntu-22.04
    if: {% raw %}${{ github.event_name == 'push' || github.event.pull_request.merged == true }}{% endraw %}
    permissions:
      contents: read
      actions: write
    steps:
      -
        name: Configure ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: {% raw %}${{ secrets.ZEROTIER_NETWORK_ID }}{% endraw %}
          auth_token: {% raw %}${{ secrets.ZEROTIER_TOKEN }}{% endraw %}
      -
        name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "{% raw %}${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}{% endraw %}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >> ~/.ssh/config <<END
          Host prod_server
            HostName {% raw %}${{ secrets.ZEROTIER_HOST }}{% endraw %}
            User {% raw %}${{ secrets.DEPLOY_SSH_USER }}{% endraw %}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
      -
        name: Check connection
        shell: bash
        run: |
          count=10
          while ! ping -c 1 {% raw %}${{ secrets.ZEROTIER_HOST }}{% endraw %} ; do
            echo "Waiting to ping...";
            sleep 1;
            let count=count-1
          done
          echo "OK: Connection established!"
      -
        name: Stop services
        run: sleep 3 && ssh prod_server 'cd {% raw %}${{ secrets.PROJECT_DIR }}{% endraw %} && docker compose down'
      -
        name: Backup
        run: ssh prod_server 'cd {% raw %}${{ secrets.PROJECT_DIR }}{% endraw %} && sudo ./scripts/backup.sh'
      -
        name: Update to latest version
        run: ssh prod_server 'cd {% raw %}${{ secrets.PROJECT_DIR }}{% endraw %} && git fetch && git reset --hard origin/production && docker compose pull'
      -
        name: Start services
        if: {% raw %}${{ always() }}{% endraw %}
        run: ssh prod_server 'cd {% raw %}${{ secrets.PROJECT_DIR }}{% endraw %} && docker compose up -d'
